### ISSUE TITLE
How to predict using another  2 images? can you help me to do this?

### ISSUE THREAD

**Issue by aliakbarhiphop** [guilhermefloriani/signature-recognition#4]

**Comment by aliakbarhiphop** [comment]
when i give 2 images, evaluate those image and predict it is genuine or not

**Comment by SiddheshSingh** [comment]
I have worked on a model as you have described. I have trained a neural network using combinations of 2 images pixel data, using three set of images: Genuine and Genuine, Genuine and Forged, and signatures of two different people. [Here is the link](https://github.com/SiddheshSingh/Signature-Recognition)
I hope it helps !
