### ISSUE TITLE
overflow encountered in exp   return 1.0 / (1.0 + np.exp(-z))

### ISSUE THREAD

**Issue by nush327** [guilhermefloriani/signature-recognition#6]
I am interested in your work. When I run the code I got following error.

RuntimeWarning: overflow encountered in exp
  return 1.0 / (1.0 + np.exp(-z))
Epoch 0: 10 / 24
Epoch 1: 10 / 24
Epoch 2: 10 / 24
Epoch 3: 10 / 24
Epoch 4: 10 / 24
Epoch 5: 10 / 24
Epoch 6: 10 / 24
Epoch 7: 10 / 24
Epoch 8: 10 / 24
Epoch 9: 10 / 24

Can you please check and let me know what went wrong in this..?

will be waiting for your reply.

thank you

**Comment by gnbaron** [comment]
So, I've replied to your email.

For other people that might find this:

*"Based on your error message my suggestion would be to investigate why the number type is overflowing when calling numpy.exp. Maybe you could use another implementation which supports larger values."*
